### PR TITLE
Fix for broken Travis build

### LINKED ISSUE #78: Travis failing under Xcode 7.3
Can anyone fix that? I just upgraded the source code to support Xcode 7.3, Swift 2.2 and Swift 3 (as stated by Xcode) and now the Travis tests are failing. Thanks!

### PR DESCRIPTION
**Pull request by davidrothera**
Fixes #78 

Also fixed broken URL links in README related to Travis build (link didn't work)

### CODE REVIEW

**Comment by skreutzberger** [comment]
... weird. I checked the Travis blog and you did everything correctly!

**Comment by davidrothera** [comment]
The travis config file states which version of Xcode / Simulator to use, these just needed bumping to 7.3 / 9.3

**Comment by davidrothera** [comment]
Looks like the build in travis is completing but the tests are failing:

```
  [Info] Collecting info for testables...2016-03-22 10:43:35.711 xctool[769:3904]  DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-10171.1/DVTFoundation/FoundationClassCategories/DVTNSBundleAdditions.m:24
Details:  Assertion failed: [NSThread isMainThread]
Function: NSBundle *_DVTFoundationBundle()
Thread:   <NSThread: 0x7fa87acb06b0>{number = 2, name = (null)}
Hints: None
Backtrace:
  0   -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _DVTAssertionFailureHandler (in DVTFoundation)
  4   _DVTFoundationBundle (in DVTFoundation)
  5   -[DVTDeveloperPaths _developerFolderPath] (in DVTFoundation)
  6   -[DVTDeveloperPaths init] (in DVTFoundation)
  7   __33+[DVTDeveloperPaths defaultPaths]_block_invoke (in DVTFoundation)
  8   _dispatch_client_callout (in libdispatch.dylib)
  9   dispatch_once_f (in libdispatch.dylib)
 10   +[DVTDeveloperPaths defaultPaths] (in DVTFoundation)
 11   __60+[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 12   _dispatch_client_callout (in libdispatch.dylib)
 13   dispatch_once_f (in libdispatch.dylib)
 14   +[SimServiceContext(DVTAdditions) dvt_sharedServiceContext:] (in DVTiPhoneSimulatorRemoteClient)
 15   __41+[DTiPhoneSimulatorSystemRoot initialize]_block_invoke (in DVTiPhoneSimulatorRemoteClient)
 16   _dispatch_client_callout (in libdispatch.dylib)
 17   dispatch_once_f (in libdispatch.dylib)
 18   +[DTiPhoneSimulatorSystemRoot initialize] (in DVTiPhoneSimulatorRemoteClient)
 19   _class_initialize (in libobjc.A.dylib)
 20   lookUpImpOrForward (in libobjc.A.dylib)
 21   objc_msgSend (in libobjc.A.dylib)
 22   +[SimulatorInfo _systemRootWithSDKPath:] (in xctool)
 23   -[SimulatorInfo simulatedDeviceInfoName] (in xctool)
 24   -[SimulatorInfo maxSdkVersionForSimulatedDevice] (in xctool)
 25   -[SimulatorInfo simulatedSdkVersion] (in xctool)
 26   -[SimulatorInfo systemRootForSimulatedSdk] (in xctool)
 27   -[SimulatorInfo simulatedRuntime] (in xctool)
 28   -[SimulatorInfo simulatedDevice] (in xctool)
 29   CreateTaskForSimulatorExecutable (in xctool)
 30   -[OCUnitIOSLogicTestQueryRunner createTaskForQuery] (in xctool)
 31   -[OCUnitTestQueryRunner runQueryWithError:] (in xctool)
 32   +[TestableExecutionInfo queryTestCasesWithSimulatorInfo:error:] (in xctool)
 33   +[TestableExecutionInfo infoForTestable:buildSettings:simulatorInfo:] (in xctool)
 34   __56-[RunTestsAction runTestables:options:xcodeSubjectInfo:]_block_invoke (in xctool)
 35   _dispatch_call_block_and_release (in libdispatch.dylib)
 36   _dispatch_client_callout (in libdispatch.dylib)
 37   _dispatch_queue_drain (in libdispatch.dylib)
 38   _dispatch_queue_invoke (in libdispatch.dylib)
 39   _dispatch_root_queue_drain (in libdispatch.dylib)
 40   _dispatch_worker_thread3 (in libdispatch.dylib)
 41   _pthread_wqthread (in libsystem_pthread.dylib)
 42   start_wqthread (in libsystem_pthread.dylib)
/Users/travis/build.sh: line 45:   769 Abort trap: 6           xctool -project SwiftyBeaver.xcodeproj -scheme SwiftyBeaver\ \(iOS\) -sdk iphonesimulator9.3 build test
```

**Comment by skreutzberger** [comment]
Some lines above it says that all tests are passing. For me all tests are working and I do not know about a test which checks for the thread.

**Comment by skreutzberger** [comment]
Can you confirm on your Mac with today’s released Xcode 7.3 that all tests are passing for you, too?

**Comment by davidrothera** [comment]
Just restarting now for the OSX update

**Comment by davidrothera** [comment]
Works fine for me :smile:

**Comment by skreutzberger** [comment]
Thanks for testing! I will send a tweet to Travis, maybe they can find the issue. It seems their Xcode 7.3 bundle does not work like a real-life Xcode 7.3

**Comment by davidrothera** [comment]
I think the issue they are seeing is the same from: https://github.com/facebook/xctool/issues/666

**Comment by skreutzberger** [comment]
:+1: I sent them a [tweet](https://twitter.com/skreutzb/status/712257206989750273) and if they do not reply I send them an email. AFAIR Travis is a Berlin company so maybe they reply soon.

**Pull request merged**
