### PR TITLE
Convert msg object to String using debugDescription

### PR DESCRIPTION
**Pull request by kuler90**

### CODE REVIEW

**Comment by skreutzberger** [comment]
Interesting PR. Can you please show an edge case where your solution works and the existing does not?

**Comment by kuler90** [comment]
Sure, for example Alamofire [result](https://github.com/Alamofire/Alamofire/blob/master/Source/Result.swift) and [responce](https://github.com/Alamofire/Alamofire/blob/master/Source/Response.swift) have different implementation for description and debugDescription, and my solution give more verbose result.

**Comment by davidrothera** [comment]
This is a nice addition, the only thing I can think of is that sometimes people may not want to use the debugDescription as it may be a little too verbose?

What is the reason why you can't explicitly call `object.debugDescription` or `object.description` in order to log?

**Comment by kuler90** [comment]
> This is a nice addition, the only thing I can think of is that sometimes people may not want to use the debugDescription as it may be a little too verbose?

You are right, sometimes it may be a little too verbose. May be verbosity should depend on the message log level? For error, warning and debug messages use debugDescription, and for info and verbose messages use simple description.

> What is the reason why you can't explicitly call object.debugDescription or object.description in order to log?

Simplicity. You may not know that the object implements verbose debugDescription.

**Comment by skreutzberger** [comment]
What if the object does not implement verbose debugDescription? Does it automatically fall back to object.description? And how often are both calls the same? In terms of implementation, maybe we add a parameter to the log command or do that level-based logic as you mention. 

But after checking docs and the usual Swift blogs I am still not fully understanding if it is a big deal or not (sorry for my ignorance)? But maybe because it is still so new?

**Comment by davidrothera** [comment]
@skreutzberger In the case that an object doesn't implement `debugDescription` it will fallback to use `description`

**Comment by skreutzberger** [comment]
I just run the `testDifferentMessageTypes()` in SwiftyBeaverTests.swift with `let msgStr = String(reflecting: msg` and I don’t see a difference. It is just different if someone wants to print a custom object? 

@davidrothera - do you see any risk in terms of user experience? Can there be weird-looking output or is it generally an improvement? If it is an improvement, should it be the default?

**Comment by davidrothera** [comment]
If the object doesn't implement `CustomStringConvertible` or `CustomDebugStringConvertible` then you just get the object, for example using `String()` or `String(reflecting:)` on a regular string gives you the same thing.

I would be wary adding this as some people might be logging objects currently (and therefore using regular description) and having clean log files, changing this if they are logging something that has a verbose debugDescription would be a bad thing.

Personally I would say the change is good as long as the user enables it when setting up the logger and default to not using the verbose `debugDescription`

```swift
import UIKit

class Test: CustomStringConvertible, CustomDebugStringConvertible {
    var debugDescription: String {
        return "this is a test"
    }

    var description: String {
        return "this is a different string"
    }
}

var la = Test()
var msg = String(la)
var msg2 = String(reflecting: la)
```

**Comment by skreutzberger** [comment]
@davidrothera :+1: 

@kuler90 Can you please extend / complete your pull request by the following 3 points so that I can merge it without changes?

1. add a public boolean called "useDebugDescription" to the top section of SwiftyBeaver’s main class with a default of `false`
2. add and wrap your changed statement in a condition that uses `useDebugDescription`. I mean String(foo) vs String(reflecting: foo)
3. add a unit test to SwiftyBeaverTests.swift to check the different output if `useDebugDescription` is `true` or `false`?

Thank you!

**Comment by kuler90** [comment]
I can, but I think this is not the best solution. Maybe better to add it later with other improvements? If you agree, you can close the PR.
P.S. I add this PR because I have own logger implementations ([first version](https://github.com/kuler90/OrangeLibrary/blob/master/Services/Log.swift), [second version](https://github.com/kuler90/OrangeFramework/tree/f685d7574c01a5aeefe1fbcbcc9e439b745ecb6a/Source/Log), [current version](https://github.com/kuler90/OrangeFramework/tree/master/Source/Log)), but I have no time to support it with rich functionality. I hope this will help you.

**Comment by prenagha** [comment]
I don't recommend this change. It is not intuitive to a user of the library that this is what the library does under the covers. Logging systems in general always use the "normal" form of stringify for an object, same as print() does. If someone wants the debug description for a special purpose they are always welcome to pass that in themselves.

**Comment by skreutzberger** [comment]
Thanks @prenagha for the comment. I am closing the PR.

**Pull request closed without merging**
