### PR TITLE
RotatingFileDestination [WIP]

### PR DESCRIPTION
**Pull request by DivineDominion**
This PR implements `RotatingFileDestination` as an adapter of `FileDestination`s that are, well, rotated when the date changes.

### CODE REVIEW

**Comment by DivineDominion** [comment]
I'm adding the PR early to get feedback before I wrap things up. I'm still implementing a `DeletionPolicy` to remove outdated files again.

**Comment by DivineDominion** [comment]
Am test-driving the changes in a beta of my own app right now.

**Comment by skreutzberger** [comment]
awesome, we will check it out!

**Comment by skreutzberger** [comment]
Sorry for the delay, I checked your code now. It seems well written and properly tested. I have several comments / questions:

1. To keep the API as clean as possible: it would be better to not expose LogDirectory as public since it is not a dedicated destination. I guess the only new API addition to the framework should be RotatingFileDestination. Is that possible?

2. Did you also test it under Linux using Docker?

3. How does your test-drive inside your app go?

**Comment by DivineDominion** [comment]
Happy to hear the code looks good to you!

1. It's not about the directory property, it's about the amount of types that are publicized, right? It makes sense to not create too much noise. I found it useful to expose the directory property, though, to inspect it later in debugging; I think one can live without it, though. Anything else I should "unpublish"?
2. Nope, and I have no clue how that works. I'll have to ask you or someone else to try that out.
3. So far it works as expected in my app ✓ 

⚠️ **A caveat concerning the rotation when deleting outdated files.** The file list filter matches the base filename in such a way that suffixes are ignored. This might remove similarly named files that were not intended for removal.

Example: When I run the app in Xcode, I append "-debug" to the file name. With a rotation set to 5 daily log files, I'd expect to have up to 5 `app.log` and `app-debug.log` each (10 files in total). But the rotation matches "app-debug", too, when it figures out which "app*.log" files are outdated, so I end up with a total of 5 log files total, debug and non-debug mixed, based on their date. 

That only concerns my development machine and doesn't trouble me much because the app has its own dedicated log file directory. But when you share a single log directory and name log files similarly, you might be surprised when only 5 files are left in total. Even though that might be considered a misconfiguration, It's something I'd like to get around fixing to not cause anybody trouble. I won't have time until February, though, to focus on the launch of my app.

**Comment by skreutzberger** [comment]
closing for now

**Comment by DivineDominion** [comment]
Bummer. Can you explain why?

@skreutzberger there's still this open question:

> It's not about the directory property, it's about the amount of types that are publicized, right? It makes sense to not create too much noise. I found it useful to expose the directory property, though, to inspect it later in debugging; I think one can live without it, though. Anything else I should "unpublish"?

I'm not willing to pour in the time to set up and get to kniw Docker to test how it works under Linux. Does this mean nobody else is?

**Comment by iadcialim** [comment]
@skreutzberger It seems @DivineDominion did a pretty good job here. Providing that file rotation (and could have added the deletion policy) is a good feature. But I sense this might have a conflict of interest with your paid cloud logging feature and that is why you are rejecting this.

**Comment by iadcialim** [comment]
@DivineDominion Have u added your features to your fork somehow? Can you share if yes?

**Comment by skreutzberger** [comment]
Hey guys. I totally forgot about that PR. It is already 4 years old and gosh, time is flying. In the meantime several users were intrested in a more sophisticated file rotation feature so I am no open to the contribution by  @DivineDominion 

Can you please update it to meet modern Swift and add tests? In that case I would be happy to receive a new PR. thank you!

**Comment by DivineDominion** [comment]
@iadcialim I am using my fork since that day and have never upgraded SwiftyBeaver :) It still works in production (macOS apps).

@skreutzberger There are tests. What are you looking for specifically?

**Pull request closed without merging**
