### PR TITLE
Made methods public for easily extending in subclass + added "user" level.

### PR DESCRIPTION
**Pull request by navisingh**
I find it very convenient to have a "user" level in addition to the usual error/warning/info/debug levels.  I use this to sprinkle user initiated code with "traceUser" entries.  What this buys me is a log containing all user initiated actions which are easy to filter.

### CODE REVIEW

**Comment by davidrothera** [comment]
User is not a level in most logging frameworks, I feel adding this doesn't really stick to the guidelines of keeping the logging system as familiar as possible. 

That's just my 2 cents though

**Comment by davidrothera** [comment]
Also, bumping of the package version should only be done by the maintainer, can you rebase that diff out of the stack please :smile:

**Comment by prenagha** [comment]
Never used nor heard of a "user" level for a logger. Seems to me we have enough logging levels already

**Comment by skreutzberger** [comment]
Yes, we should stick to the existing log levels to not confuse the majority of users.

**Pull request closed without merging**
