### PR TITLE
Elastic Search

### PR DESCRIPTION
**Pull request by kostyan5**
Added support to post to ElasticSearch using Bulk API

### CODE REVIEW

**Comment by skreutzberger** [comment]
Thanks for the PR and it makes more than sense to re-use the platform destination and just change the endpoint and remove the e2e encryption. 

I have several questions for better understanding:
1. You do the auth to the ElasticSearch server via the `additionalHttpHeaders`? Can you simplify that or does it need to be so generic?
2. Currently you store device data separate from the log entries. How do you bring them both together on the ES-side? In the platform destination they are separate because they are "linked" together in the Mac App via SQLite.
3. Do you use that already somewhere and with what authentication?
4. Can you confirm that you see all entries + device details with Kibana?

**Comment by kostyan5** [comment]
1. By default, ElasticSearch API is open and doesn't support authentication per se.  So it's up to the user to add a gateway in front of ElasticSearch if they want it to be accessible from outside their internal network.  For my use case, I use AWS ElasticSearch Service and configure it to be accessible through AWS API Gateway only.  This api is secured via x-api-key token in the header.  Other people may have different use cases.  For example, another auth method may have a "Authorization" header or something else entirely, such as AWS IAM signing.  Not sure the best way to simplify this.

2.  I added UUID into log entries.  You can use ElasticSearch queries to look up analytics by searching for that UUID.

3. Yes, described in answer to 1

4. Yes, see screenshots below.

One thing I may end up doing is changing the timestamp from Unix Epoch to ISO8061.  Otherwise, 
ElasticSearch doesn't automatically detect it as 'date' in the mapping, it flags it as Long or Float.  In which case, you need to manually create the mapping for timestamp in order to get timeseries in kibana.  Changing timestamp to ISO8061 is trivial.  I'll send another PR with it, I made a few other changes, such as adding logLevel word in addition to int.

screen shot 2017-09-01 at 9 56 38 am
screen shot 2017-09-01 at 9 56 25 am

**Comment by kostyan5** [comment]
Didn't realize updating my master was automatically update the PR, so you already have the logLevel word.  I'll add and test ISO8061 date today as well.

**Comment by kostyan5** [comment]
Due to some limitations in AWS ElasticSearch Service, using a simple api key header is not possible.  I reworked ElasticSearch destination to be a bit more generic by accepting a closure that will do request signing.  I based this on the way AWS SDK intercepts URLRequests to do their own signing.  For example, this is how we now sign the ElasticSearch destination requests:

`class AWSESEndpoint: AWSEndpoint {
    override var serviceName: String! {
        return "es"
    }
}

func awsSigner(request: inout URLRequest) {
    guard let accessKey = Settings.sharedInstance.awsAccessKey, let secretKey = Settings.sharedInstance.awsSecretKey else {
        log.error("Missing AWS Access and/or Secret key")
        return
    }
    
    let credProv = AWSStaticCredentialsProvider(accessKey: accessKey, secretKey: secretKey)
    let endPoint = AWSESEndpoint(region: .USWest2, service: .Unknown, url: request.url)
    
    guard let signer   = AWSSignatureV4Signer(credentialsProvider: credProv, endpoint: endPoint) else {
        log.error("Invalid AWS signer (incorrect keys)")
        return
    }
    
    guard let req = request as? NSMutableURLRequest else { log.error("Invalid URLRequest"); return }
    
    let group = DispatchGroup()
    group.enter()
    AWSNetworkingRequestInterceptor().interceptRequest(req).continueWith { _ in     // adds "X-Amz-Date" header
        group.leave()
    }
    group.enter()
    signer.interceptRequest(req).continueWith { _ in                                // signs request
        group.leave()
    }
    group.wait()                                                                    // wait for all interceptors to finish
    
    request = req as URLRequest
}
`

**Comment by aharin** [comment]
I am very interested to get this feature complete. I spiked it out on my own fork and did manage to get it working with Cognito. There are a couple of things that I would like to fix though.

- Kibana works best with index patterns that have a date suffix, rather then just having one index. 
- Kibana does not recognise the timestamp field as it is in the wrong format.
- I think analytics info should be denormalised and just added to the log records rather then sent to a separate index.

Also it would be good to make base methods/fields on the BaseDestination open so that a new destination could be developed without forking the whole project.

Happy to help with these changes!

**Comment by skreutzberger** [comment]
closing this for now

**Pull request closed without merging**
