### PR TITLE
Updated Swift syntax

### PR DESCRIPTION
**Pull request by brl214**
Updated Swift 3 Syntax for Xcode 8 for:

AES256CBC.swift
FileDestination.swift
SBPlatformDestination.swift
SwiftyBeaver.swift

Won't compile without these changes.

### CODE REVIEW

**Comment by skreutzberger** [comment]
What Swift version is it? The swift3 branch is already using the latest Swift of Xcode 8 Beta 3.

**Comment by brl214** [comment]
Swift 3.0 Preview 2. I had 25 errors when I tried to compile.

**Comment by brl214** [comment]
Yeah completely ignore this I didn't realize I was still on preview 2. Sorry :(

**Comment by skreutzberger** [comment]
No worries, I also got confused about what the latest beta version is. I can’t wait until Swift 3 is finally released.

**Pull request closed without merging**
