### PR TITLE
Adds 'uptime' of the log's destination as possible format string

### PR DESCRIPTION
**Pull request by LordNali**
Added a new format argument 'U' to include the log's destination (!) uptime down to milliseconds.

I'm aware this isn't the actual system uptime or the running App's uptime either, but for our purpose it's perfect - we simply need a relative time in our logs.

So up to discussion:
- Should it rather be called relativeTime(span)
- Is there a better place for 'startDate' then each log's destination
- Should we go for an actual system uptime

### CODE REVIEW

**Comment by skreutzberger** [comment]
Interesting idea! So it means how long the app is "up" / "alive"? Do you use it for mobile or on desktop or server?

**Comment by LordNali** [comment]
We're using it for a mobile App.

For us the actual date of a log entry is not relevant, we're only interested in their relative time. It would even better to get the actual uptime / starttime of an App. But since an App could basically run forever (moved to the background by iOS itself) this probably makes no sense - for a server environment on the other hand...

**Comment by LordNali** [comment]
Is there still interest in this PR or must it be closed?

**Comment by skreutzberger** [comment]
Yes, there is still interest and I want to merge it into master. I hesitated because was just thinking if there is a way to test it. I guess there is not?
In our tests we have some examples of how to test the log output but since your test is time based?!

**Comment by LordNali** [comment]
Testing it is indeed not so trivial - at least in your UnitTests. On the other hand we would use this logging format from now on, therefore we would detect any issue immediately ;-)

**Comment by skreutzberger** [comment]
I run some tests and it works. I merged it into master and it is part of the next release coming next week. Thanks for the contribution!

**Pull request merged**
