### PR TITLE
Create Package@swift-4.2.swift

### PR DESCRIPTION
**Pull request by heyzooi**
Better support for Swift 4.2

### CODE REVIEW

**Comment by skreutzberger** [comment]
Great, thanks again!

**Comment by MKGitHub** [comment]
Why is it called "Package@swift-4.2.swift" ?

**Comment by heyzooi** [comment]
if you are using Swift 4.2 it will try to use this file first, otherwise it will default to the regular `Package.swift` file

**Comment by skreutzberger** [comment]
Your pull request is now live in version 1.6.2. Thanks again for contributing!

**Pull request merged**
