### PR TITLE
Fix issue 224, build invalid framework for macOS

### PR DESCRIPTION
**Pull request by alex-chan**
https://github.com/SwiftyBeaver/SwiftyBeaver/issues/224
The reason is source files is not contained in target macOS(and others except iOS)

### CODE REVIEW

**Comment by skreutzberger** [comment]
that is weird since lots of people are using SwiftyBeaver on other platforms. Can you confirm that it is truly an issue?

**Comment by alex-chan** [comment]
Er.. There is no files in the `Compile Sources` section under `Build Phases` tab for target macOS,(and tvOS, watchOS), so I can only build a framework without any source.
you can try it yourself or ask someone else to confirm it if you are not very sure about the correctness of this pull request.

**Comment by skreutzberger** [comment]
I can confirm your pull request is working. It seems one of the recent changes somehow deleted these compile sources. Thanks for adding them again!

**Comment by skreutzberger** [comment]
... and sorry for my delayed response.

**Pull request merged**
